name: CI
on: [push]
jobs:
  smoke-test:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - run: make test
        name: Test
